# This is a basic workflow to help you get started with Actions

name: DS918P-Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DS918P_PID: ${{ secrets.DS918P_PID }}
  DS918P_VID: ${{ secrets.DS918P_VID }}
  DS918P_SN: ${{ secrets.DS918P_SN }}
  DS918P_MAC: ${{ secrets.DS918P_MAC }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: build
        run: |
          git clone https://github.com/guigeng/redpill-tool-chain redpill-tool-chain
          cd redpill-tool-chain
          chmod +x redpill_tool_chain.sh
          sed -i "s/1234XXX123/${DS918P_SN}/g" apollolake_user_config.json
          sed -i "s/XXYYXXYYXXYY/${DS918P_MAC}/g" apollolake_user_config.json
          sed -i "s/0x46f4/${DS918P_VID}/g" apollolake_user_config.json
          sed -i "s/0x0001/${DS918P_PID}/g" apollolake_user_config.json

          cat apollolake_user_config.json
          ./redpill_tool_chain.sh build apollolake-7.0.1-42214
          ./redpill_tool_chain.sh auto apollolake-7.0.1-42214
          ls -l
          sudo mkdir firmware
          sudo mv images/*.img firmware/
          curl -sL https://git.io/file-transfer | sh 
          sudo ./transfer wet firmware/
